<?php
return array(
    'install_title' => 'Album Service Installation Wizard',
    'step_env' => 'Environment Check',
    'step_config' => 'Admin Setup',
    'step_finish' => 'Complete',
    'php_version' => 'PHP Version',
    'ext_exif' => 'EXIF Extension',
    'ext_gd' => 'GD Extension',
    'ext_imagick' => 'ImageMagick Extension',
    'dir_writable' => 'Directory Permissions',
    'btn_next' => 'Next',
    'btn_start' => 'Start Installation',
    'admin_user' => 'Admin Username',
    'admin_pass' => 'Admin Password',
    'site_name' => 'Album Title',
    'install_success' => 'Album Service installed successfully!',
    'install_error' => 'Installation error:',
    'delete_install' => 'For security reasons, please delete install.php after completion.',
    'goto_admin' => 'Go to Admin Panel',
    'goto_album' => 'Open Album',
    'theme_select' => 'Default Theme',
    'api_type' => 'Data Reading Mode',
    'items_per_page' => 'Items Per Page',
    'api_json' => 'Static JSON Mode (Recommended)',
    'api_php' => 'Dynamic PHP API Mode',
    'admin_settings' => 'Admin Settings',
    'frontend_settings' => 'Frontend Display Settings',
    'timezone' => 'System Timezone'
);
