<?php
return array(
    'install_title' => '相簿服務安裝精靈',
    'step_env' => '環境檢測',
    'step_config' => '帳號設定',
    'step_finish' => '完成安裝',
    'php_version' => 'PHP 版本',
    'ext_exif' => 'EXIF 擴充 (照片資訊)',
    'ext_gd' => 'GD 擴充 (縮圖生成)',
    'ext_imagick' => 'ImageMagick 擴充 (高品質縮圖)',
    'dir_writable' => '目錄寫入權限',
    'btn_next' => '下一步',
    'btn_start' => '開始安裝',
    'admin_user' => '管理員帳號',
    'admin_pass' => '管理員密碼',
    'site_name' => '相簿名稱',
    'install_success' => '相簿服務安裝成功！',
    'install_error' => '安裝過程中發生錯誤：',
    'delete_install' => '為了安全起見，請在安裝完成後刪除 install.php 檔案。',
    'goto_admin' => '前往管理後台',
    'goto_album' => '開啟相簿首頁',
    'theme_select' => '預設主題',
    'api_type' => '資料讀取模式',
    'items_per_page' => '每頁顯示項目數',
    'api_json' => '靜態 JSON 模式 (推薦)',
    'api_php' => '動態 PHP API 模式',
    'admin_settings' => '後台管理設定',
    'frontend_settings' => '前端顯示設定',
    'timezone' => '系統時區'
);
