<?php
// langs/admin/en_US.php
return [
    // Login
    'login_title' => 'Blog Admin Panel',
    'login_username' => 'Username',
    'login_password' => 'Password',
    'login_mode' => 'Management Mode',
    'login_btn' => 'Login',
    'login_back_home' => 'Back to Blog Home',
    'error_auth_fail' => 'Invalid username or password',
    'login_locked_msg' => 'Too many failed attempts. Your IP has been locked for 15 minutes.',
    'login_failed_msg' => 'Invalid credentials. %d attempts remaining.',
    'error_mode_unavailable' => 'The selected mode is unavailable. Please check the environment.',
    'mode_db' => 'Database',
    'mode_file' => 'File System',
    'db_init_msg' => 'Database not initialized.',
    'db_init_link' => 'Click here to initialize',
    'file_init_msg' => 'File system structure incomplete.',
    'file_init_link' => 'Click here to build structure',
    'select_lang' => 'Language',

    // Health Check
    'health_db_connected' => 'Connected (Posts: %d)',
    'health_db_table_missing' => 'Connected, but table \'blog_posts\' missing',
    'health_db_conn_fail' => 'Connection Failed: %s',
    'health_file_ok' => 'File Structure Valid',
    'health_file_missing_index' => 'Missing contents/index_post.txt',
    'health_file_missing_posts' => 'Missing contents/post_files directory',
    'health_file_missing_cat' => 'Missing category directory',

    // Navigation & Layout
    'nav_brand' => 'Blog Admin',
    'nav_dashboard' => '📊 Dashboard',
    'nav_posts' => '📝 Posts',
    'nav_categories' => '📂 Categories',
    'nav_import' => '🔄 Data Migration',
    'nav_preview' => '🌍 Preview Site',
    'nav_logout' => '🚪 Logout',
    'mode_label' => 'Mode',
    'mode_db_short' => 'Database',
    'mode_file_short' => 'File System',

    // Dashboard
    'welcome_msg' => 'Welcome Back',
    'stat_posts' => 'Total Posts',
    'stat_published' => 'Published',
    'stat_drafts' => 'Drafts',
    'stat_posts_sub' => 'published posts',
    'stat_db_size' => 'DB Size',
    'stat_disk_free' => 'Disk Free',
    'stat_disk_total' => 'Total',
    'stat_connection' => 'Connection Info',
    'not_applicable' => 'N/A',
    'recent_posts_title' => '🚀 Recent Posts',
    'col_date' => 'Date',
    'col_title' => 'Title',
    'no_posts' => 'No posts found.',
    'view_all_posts' => 'Manage All Posts',

    // Posts Management
    'posts_list_title' => '📂 Post List',
    'btn_new_post' => '+ New Post',
    'msg_deleted' => 'Post deleted successfully.',
    'col_post_info' => 'Post Info (Title/File/Desc)',
    'col_category' => 'Category',
    'col_tags' => 'Tags',
    'col_action' => 'Actions',
    'no_title' => 'No Title',
    'btn_edit' => 'Edit',
    'btn_delete' => 'Delete',
    'confirm_delete_title' => 'Are you sure?',
    'confirm_delete_text' => 'You won\'t be able to revert this!',
    'confirm_yes' => 'Yes, delete it!',
    'confirm_cancel' => 'Cancel',
    'swal_deleted_title' => 'Deleted!',
    'swal_deleted_text' => 'Your post has been deleted.',

    // Categories Management
    'cat_title' => '📂 Categories',
    'btn_add_cat' => '+ New Category',
    'cat_hint' => 'Hint: Manage your categories here. You can add, rename, or remove categories. Removing a category will NOT delete the posts within it.',
    'cat_count_suffix' => 'posts',
    'btn_rename' => 'Rename',
    'btn_remove' => 'Remove',
    'no_categories' => 'No categories found.',
    
    // Modals
    'modal_create_title' => 'New Category',
    'modal_cat_name' => 'Category Name',
    'btn_create' => 'Create',
    'modal_rename_title' => 'Rename Category',
    'modal_old_name' => 'Old Name',
    'modal_new_name' => 'New Name',
    'modal_rename_warn' => 'Warning: This will update all posts associated with this category.',
    'btn_confirm_modify' => 'Update',
    'modal_remove_title' => 'Remove Category',
    'modal_remove_confirm' => 'Are you sure you want to remove ',
    'modal_remove_confirm_suffix' => '?',
    'modal_remove_hint' => 'This will remove the category tag from all posts, but the posts themselves will remain.',
    'btn_confirm_remove' => 'Remove',

    // Messages
    'msg_rename_success' => 'Successfully renamed category from \"%s\" to \"%s\".',
    'msg_rename_fail' => 'Rename failed or category not found.',
    'msg_remove_success' => 'Successfully removed category \"%s\".',
    'msg_remove_fail' => 'Remove failed or category not found.',
    'msg_create_success' => 'Successfully created category \"%s\".',
    'msg_create_fail' => 'Creation failed. Category might already exist.',

    // Post Edit
    'edit_title_new' => 'New Post',
    'edit_title_edit' => 'Edit Post',
    'post_not_found' => 'Post not found',
    'breadcrumb_home' => 'Posts',
    'label_post_title' => 'Title',
    'label_filename' => 'Filename (Optional, auto date prefixed)',
    'ph_filename' => 'e.g. tokyo-travel (Auto: 20250101-tokyo-travel.html)',
    'label_post_date' => 'Date',
    'label_html_content' => 'HTML Content',
    'hint_html_content' => 'Enter raw HTML here. Use &lt;!--more--&gt; for summary break.',
    'label_categories' => 'Categories',
    'label_add_category' => 'Add Category',
    'ph_new_category' => 'New category name',
    'label_tags' => 'Tags',
    'ph_tags' => 'Comma separated, e.g., Photo, Life, Tech',
    'label_desc' => 'Meta Description',
    'hint_desc_seo' => 'This text appears in search results. A good description improves SEO rankings.',
    'ph_desc_seo' => 'Enter a brief summary (recommended under 160 characters)',
    'label_preview_image' => 'SEO Preview Image (OG Image)',
    'hint_preview_image' => 'Upload a representative image for this post. System will auto-crop to 1200x630.',
    'msg_preview_exists' => 'Preview image exists',
    'label_auto_build' => 'Rebuild static pages immediately after saving',
    'btn_cancel' => 'Cancel',
    'btn_save' => 'Save Post',
    'btn_save_draft' => 'Save Draft',
    'btn_save_publish' => 'Publish',

    // Vibe Info
    'vibe_info' => 'Vibe coded with Gemini CLI & Gemini AI Models',

    // Migrate Tool
    'migrate_title' => 'Data Migration Tool',
    'migrate_info_title' => 'Info',
    'migrate_desc' => 'Migrates content from \"File System\" to the designated database (MySQL or SQLite).',
    'migrate_warn' => 'Note: If a post with the same filename exists in DB, it will be UPDATED. Otherwise, it will be INSERTED.',
    'db_status' => 'Target Database Status',
    'btn_start_migration' => '🚀 Start Migration',
    'confirm_start_migration' => 'Are you sure? This might take a while.',
    'btn_db_unreachable' => 'Database Unreachable',
    'log_header' => 'Execution Log',
    'log_connecting' => 'Connecting to database...', 
    'log_connected' => 'Connected successfully!',
    'log_file_missing' => 'Index file not found: %s',
    'log_start_process' => 'Processing %d posts...', 
    'log_imported' => 'Imported: %s',
    'log_failed' => 'Failed [%s]: %s',
    'log_complete' => 'Migration Complete! Success: %d',
    'log_sys_error' => 'System Error: %s',

    // Migrate Tool - New
    'migrate_export_to_db' => '1. Export to DB (File &rarr; DB)',
    'migrate_target_db' => 'Target DB:',
    'migrate_restore_from_db' => '2. Restore from DB (DB &rarr; File)',
    'migrate_source_db' => 'Source DB:',
    'migrate_current_mode' => 'Current Mode:',
    'migrate_export_data' => '1. Export Data',
    'migrate_export_desc' => 'Export current DB content to...',
    'migrate_target_loc' => 'Target:',
    'migrate_import_data' => '2. Import Data',
    'migrate_import_desc' => 'Import from external source to current DB...',
    'migrate_source_loc' => 'Source:',
    'btn_start_restore' => '📥 Start Restore',
    'btn_exec_export' => '📤 Execute Export',
    'btn_exec_import' => '📥 Execute Import',
    'confirm_export_warn' => 'Are you sure? Target data will be overwritten/updated.',
    'confirm_import_warn' => 'Are you sure? Existing posts with same filename will be updated.',
    'confirm_restore_warn' => 'Are you sure? This will overwrite the contents directory.',
    'log_db_connect_fail' => 'Cannot connect to source database',
    'log_target_connect_fail' => 'Target database connection failed: %s',
    'log_target_connect_success' => 'Target database connected: %s',
    'log_reading_source' => 'Reading source database...',
    'log_found_posts' => 'Found %d posts',
    'log_exported' => 'Exported: %s',
    'log_export_complete' => 'Export complete! index_post.txt updated.',
    'log_prepare_migration' => 'Preparing migration: %s -> %s',
    'log_source_count' => 'Source data: %d rows',
    'log_migration_success' => 'Success: %s',
    'log_migration_fail' => 'Fail: %s',
    'log_migration_complete' => 'Database migration complete!',
    'log_migration_error' => 'Migration error: %s',

    // SQLite Init
    'sqlite_init_title' => 'SQLite Initialization',
    'sqlite_init_msg' => 'You have enabled SQLite mode, but the database file is not initialized.',
    'sqlite_enter_pass' => 'Please enter admin password to continue:',
    'sqlite_verify_btn' => 'Verify',
    'sqlite_init_options' => 'Initialization Options',
    'sqlite_import_file' => '📂 Import from File System',
    'sqlite_import_file_desc' => 'Import existing file posts to SQLite',
    'sqlite_import_mysql' => '🐬 Import from MySQL',
    'sqlite_import_mysql_desc' => 'Copy data from MySQL to SQLite',
    'sqlite_clean_install' => '🆕 Clean Install',
    'sqlite_clean_install_desc' => 'Create an empty database',
    'sqlite_goto_admin' => 'Go to Admin Panel',
    'sqlite_auth_fail' => 'Authentication failed',
    'sqlite_init_success' => 'SQLite database initialized successfully!',
    'sqlite_init_fail' => 'Initialization failed: %s',
    'sqlite_conn_fail' => 'Cannot connect to SQLite. Check path permissions.',
    'sqlite_sample_title' => 'Welcome to BaxerMux Blog (SQLite)',
    'sqlite_sample_content' => '<p>This is a sample post for SQLite version.</p>',

    // Admin Index Hardcoded
    'stat_mode_file' => 'Mode: File System',
    'stat_path' => 'Path: contents/',
    'stat_log' => 'Log: index_post.txt',
    'stat_type' => 'Type: %s',
    'stat_ver' => 'Ver: %s',
    'stat_driver' => 'Driver: %s',

    // Health Check New
    'health_php_pdo_missing' => 'PHP PDO Extension missing',
    'health_php_mysql_missing' => 'PHP PDO MySQL Driver missing',
    'health_sqlite_config_missing' => 'Config $sqlite_path not set',
    'health_php_sqlite_missing' => 'PHP PDO SQLite Driver missing',
    'health_sqlite_file_missing' => 'SQLite file missing',
    'health_sqlite_ready' => 'SQLite Ready (Posts: %d)',
    'health_sqlite_table_missing' => 'SQLite Tables Missing',
    'health_sqlite_error' => 'SQLite Error: %s',
    'health_album_ready' => 'Album Service Ready (Path found)',
    'health_album_not_set' => 'Album Path Not Set',
    'health_album_not_found' => 'Album Path Not Found',

    'album_service_title' => 'Album Service',
    'album_manage_btn' => 'Manage',
    'album_manage_hint' => 'Go to Album Admin &rarr;',
    'btn_pick_from_album' => 'Select from Album',
    'modal_album_picker_title' => 'Select Image from Album',
    'btn_back_to_albums' => 'Back to Albums',
    'album_loading' => 'Loading albums...',
    'photo_loading' => 'Loading photos...',
    'no_albums_found' => 'No albums found.',
    'no_photos_found' => 'No photos in this album.',
    'label_album_name' => 'Album: ',
    'btn_direct_upload' => 'Upload to this album',
    'uploading_wait' => 'Uploading and generating thumbnails...',
    'msg_selected' => 'Selected: ',
    'btn_size_original' => 'Original',
    'btn_size_large' => 'Large (1600px)',
    'btn_size_medium' => 'Medium (800px)',
    'close_btn' => 'Close',

    // Backup Tool
    'nav_backup' => '📦 Backup',
    'nav_settings' => '⚙️ Settings',
    'backup_title' => 'System Backup',

    // Settings
    'settings_title' => 'Site Configuration',
    'section_backend' => 'Backend Core Settings (config.php)',
    'label_blog_title' => 'Blog Title',
    'label_blog_description' => 'Blog SEO Description',
    'label_blog_introduce' => 'Blog Introduction',
    'section_frontend' => 'Frontend Interface Settings (config.js)',
    'label_api_type' => 'Data Source (API Type)',
    'label_blog_lang' => 'Blog Language',
    'label_timezone' => 'Timezone',
    'label_album_path' => 'Album Service Path',
    'hint_album_path' => 'Set the relative path of the album service from the blog root (default: album/).',
    'label_posts_per_page' => 'Posts Per Page (Backend)',
    'hint_posts_per_page' => 'Controls how many posts the Server API returns per page in dynamic mode.',
    'label_blog_favicon' => 'Blog Favicon Path',
    'hint_blog_favicon' => 'Set the site favicon path (default: /static/icon-192.png).',
    'label_posts_per_page_js' => 'Posts Per Page (Frontend)',
    'hint_posts_per_page_js' => 'Mainly used for "Static JSON" mode to control client-side pagination.',
    'lang_zh_tw' => 'Traditional Chinese',
    'lang_en_us' => 'English',
    'label_theme' => 'Site Theme',
    'label_cse_id' => 'Google CSE ID',
    'label_guestbook_plugin' => 'Guestbook Plugin Path',
    'hint_guestbook_plugin' => 'Path to the MessageBoard plugin script (leave empty to disable).',
    'label_guestbook_per_page' => 'Guestbook Per Page',
    'msg_settings_saved' => 'Settings saved successfully!',
    'error_config_write' => 'Failed to write config.js. Check permissions.',
    'opt_api_file' => 'File System',
    'opt_api_db' => 'MySQL Database',
    'opt_api_sqlite' => 'SQLite Database',
    'btn_save_settings' => 'Save Settings',
    'backup_create_title' => 'Create New Backup',
    'backup_desc' => 'System will pack all necessary data and resources based on current mode (File or DB). This may take a few minutes.',
    'backup_confirm' => 'Start backup? Please wait patiently.',
    'btn_create_backup' => 'Create ZIP Backup',
    'backup_list_title' => 'Backup List',
    'backup_success' => 'Backup Successful',
    'backup_fail' => 'Backup Failed. Check permissions.',
    'backup_deleted' => 'Backup deleted.',
    'col_filename' => 'Filename',
    'col_size' => 'Size',
    'col_time' => 'Time',
    'btn_download' => 'Download',
    'confirm_delete_backup' => 'Delete this backup?',
    'no_backups' => 'No backups found.',
    'btn_restore' => 'Restore',
    'confirm_restore_title' => 'Confirm Restore?',
    'confirm_restore_text' => 'This will OVERWRITE existing data and files!',
    'restore_success' => 'System restored successfully!',
    'restore_fail' => 'Restore failed. Format error or cannot open ZIP file.',
    'loading_backup' => 'Creating backup, please wait...',
    'loading_restore' => 'Restoring system, please do not close...',
    'loading_upload' => 'Uploading backup file, please wait...',
    'btn_confirm_yes' => 'Yes, do it!',
    'btn_confirm_cancel' => 'Cancel',
    'backup_upload_title' => 'Upload Backup',
    'backup_upload_desc' => 'You can upload backup files (ZIP) from other hosts for restoration.',
    'php_ini_hint_title' => 'PHP Configuration Hint',
    'php_ini_hint_desc' => 'For large file uploads, please ensure the following php.ini settings are adjusted appropriately. Restart the server after changes:',
    'php_ini_hint_example' => 'Example Settings:',
    'php_ini_hint_fail' => 'If settings cannot be changed or the file exceeds limits, please upload via FTP to the backup directory and then restore.',
    'btn_select_file' => 'Select File',
    'btn_upload' => 'Upload',
    'upload_success' => 'Backup uploaded successfully!',
    'upload_fail' => 'Upload failed! Possible reasons: File exceeds system limit (%s) or permission denied. If file is too large, please use FTP to upload to "backup" directory.',
    'upload_err_format' => 'Error: Only ZIP files allowed.',
    'upload_limit_hint' => 'Note: System upload limit is approx %s. If the file exceeds this, upload will fail. Please use FTP or other methods to place the file in the "backup" directory.',
    'op_success' => 'Operation Successful',
    'op_error' => 'Operation Failed',

    // Build Tool (SSG)
    'nav_build' => '🔨 Build Site',
    'build_title' => 'Static Site Generation (SSG)',
    'build_desc' => 'This tool manually triggers the generation of static HTML pages and the JSON API based on current post data.',
    'label_build_options' => 'Build Options',
    'opt_force_all' => 'Force Rebuild All (Ignore cache)',
    'opt_update_json' => 'Update JSON API (data.json)',
    'opt_force_global' => 'Force Rebuild Global Pages (Home/List)',
    'label_select_posts' => 'Select Specific Posts (Scan all changes if none selected)',
    'btn_start_build' => '🚀 Start Build Process',
    'build_log_title' => 'Build Log',
    'build_running' => 'Building, please wait...',
    'build_complete' => 'Build completed!',
    'col_select' => 'Select',
    'filter_all' => 'All',
    'filter_published' => 'Published Only',
    'badge_no_static' => 'Static Page Missing',
    'stat_no_static' => 'Unbuilt',

    // Security Warning
    'warn_install_file_exists' => '⚠️ Security Warning: Installer file (install.php) still exists.',
    'warn_install_file_exists_desc' => 'For security reasons, please manually delete <code>install.php</code> from your root directory after installation.',
];