<?php
// langs/admin/zh_TW.php
return [
    // Login
    'login_title' => 'Blog 後台管理',
    'login_username' => '帳號',
    'login_password' => '密碼',
    'login_mode' => '管理模式',
    'login_btn' => '登入',
    'login_back_home' => '回到部落格首頁',
    'error_auth_fail' => '帳號或密碼錯誤',
    'login_locked_msg' => '嘗試次數過多，帳號已暫時鎖定 15 分鐘。',
    'login_failed_msg' => '登入失敗。您還有 %d 次嘗試機會。',
    'error_mode_unavailable' => '選定的管理模式目前不可用，請檢查系統環境。',
    'mode_db' => '資料庫 (Database)',
    'mode_file' => '檔案系統 (File System)',
    'db_init_msg' => '資料庫尚未初始化。',
    'db_init_link' => '點擊此處進行初始化設定',
    'file_init_msg' => '檔案系統結構不完整。',
    'file_init_link' => '點擊此處進行建構設定',
    'select_lang' => '語言 / Language',

    // Health Check
    'health_db_connected' => '連線成功 (文章數: %d)',
    'health_db_table_missing' => '連線成功，但找不到資料表 \'blog_posts\'',
    'health_db_conn_fail' => '連線失敗: %s',
    'health_file_ok' => '檔案結構完整',
    'health_file_missing_index' => '缺少 contents/index_post.txt',
    'health_file_missing_posts' => '缺少 contents/post_files 目錄',
    'health_file_missing_cat' => '缺少 category 目錄',

    // Navigation & Layout
    'nav_brand' => 'Blog Admin',
    'nav_dashboard' => '📊 儀表板',
    'nav_posts' => '📝 文章管理',
    'nav_categories' => '📂 分類管理',
    'nav_import' => '🔄 資料遷移',
    'nav_preview' => '🌍 預覽網站',
    'nav_logout' => '🚪 登出',
    'mode_label' => '模式',
    'mode_db_short' => '資料庫',
    'mode_file_short' => '檔案系統',

    // Dashboard
    'welcome_msg' => '歡迎回來',
    'stat_posts' => '文章總數',
    'stat_published' => '已發布',
    'stat_drafts' => '草稿',
    'stat_posts_sub' => '篇已發布文章',
    'stat_db_size' => '資料庫大小',
    'stat_disk_free' => '磁碟剩餘空間',
    'stat_disk_total' => '總容量',
    'stat_connection' => '連線資訊',
    'not_applicable' => '不適用',
    'recent_posts_title' => '🚀 最新發布文章',
    'col_date' => '發布日期',
    'col_title' => '標題',
    'no_posts' => '目前沒有文章',
    'view_all_posts' => '管理所有文章',

    // Posts Management
    'posts_list_title' => '📂 文章列表',
    'btn_new_post' => '+ 撰寫新文章',
    'msg_deleted' => '文章已刪除。',
    'col_post_info' => '文章資訊 (標題/檔名/描述)',
    'col_category' => '分類',
    'col_tags' => '標籤',
    'col_action' => '操作',
    'no_title' => '無標題',
    'btn_edit' => '編輯',
    'btn_delete' => '刪除',
    'confirm_delete_title' => '確定要刪除這篇文章嗎？',
    'confirm_delete_text' => '這個動作無法復原！',
    'confirm_yes' => '是的，刪除它！',
    'confirm_cancel' => '取消',
    'swal_deleted_title' => '已刪除！',
    'swal_deleted_text' => '文章已成功移除。',

    // Categories Management
    'cat_title' => '📂 分類管理',
    'btn_add_cat' => '+ 新增分類',
    'cat_hint' => '提示：此處列出系統中的所有分類。您可以新增、改名或移除分類。請注意，移除分類不會刪除該分類下的文章。',
    'cat_count_suffix' => '篇文章',
    'btn_rename' => '改名',
    'btn_remove' => '移除',
    'no_categories' => '目前沒有任何分類資料。',
    
    // Modals
    'modal_create_title' => '新增分類',
    'modal_cat_name' => '分類名稱',
    'btn_create' => '建立',
    'modal_rename_title' => '重新命名分類',
    'modal_old_name' => '原名稱',
    'modal_new_name' => '新名稱',
    'modal_rename_warn' => '注意：這將會批次修改所有相關的文章資料。',
    'btn_confirm_modify' => '確認修改',
    'modal_remove_title' => '移除分類',
    'modal_remove_confirm' => '您確定要移除分類',
    'modal_remove_confirm_suffix' => '嗎？',
    'modal_remove_hint' => '這將會從所有相關的文章中刪除此分類標籤，但文章本身不會被刪除。',
    'btn_confirm_remove' => '確認移除',

    // Messages
    'msg_rename_success' => '成功將分類由「%s」改為「%s」。',
    'msg_rename_fail' => '修改失敗或未找到目標。',
    'msg_remove_success' => '成功移除分類「%s」。',
    'msg_remove_fail' => '移除失敗或未找到目標。',
    'msg_create_success' => '成功建立新分類「%s」。',
    'msg_create_fail' => '建立失敗，可能分類已存在。',

    // Post Edit
    'edit_title_new' => '撰寫新文章',
    'edit_title_edit' => '編輯文章',
    'post_not_found' => '文章不存在',
    'breadcrumb_home' => '文章管理',
    'label_post_title' => '文章標題',
    'label_filename' => '檔案名稱 (選填，系統自動加上日期前綴)',
    'ph_filename' => '例如: tokyo-travel (自動生成 20250101-tokyo-travel.html)',
    'label_post_date' => '發布時間',
    'label_html_content' => 'HTML 內容',
    'hint_html_content' => '請直接輸入 HTML 原始碼。可使用 &lt;!--more--&gt; 設定摘要分隔線。',
    'label_categories' => '文章分類',
    'label_add_category' => '新增分類',
    'ph_new_category' => '輸入新分類名稱',
    'label_tags' => '標籤 (Tags)',
    'ph_tags' => '使用逗號分隔，例如: 攝影, 開箱, 心得',
    'label_desc' => '摘要描述 (Meta Description)',
    'hint_desc_seo' => '這段文字會出現在搜尋引擎結果中，良好的描述有助於 SEO 排名。',
    'ph_desc_seo' => '請輸入簡短的文章摘要 (建議 160 字以內)',
    'label_preview_image' => 'SEO 預覽圖 (OG Image)',
    'hint_preview_image' => '上傳一張代表此文章的圖片，系統將自動裁切為 1200x630。',
    'msg_preview_exists' => '預覽圖已存在',
    'label_auto_build' => '儲存後立即重建靜態網頁',
    'btn_cancel' => '取消',
    'btn_save' => '儲存文章',
    'btn_save_draft' => '暫存草稿',
    'btn_save_publish' => '正式發布',

    // AI Assistant
    'btn_ai_assistant' => 'AI 輔助優化',
    'modal_ai_title' => 'AI 專家輔助功能',
    'modal_ai_desc' => 'AI 將分析您的文章內容，並自動產生標題、建議檔名、SEO 摘要以及修潤內文。',
    'btn_ai_analyze' => '開始 AI 分析',
    'btn_ai_apply' => '確認並套用結果',
    'label_ai_suggest_title' => 'AI 建議標題',
    'label_ai_suggest_filename' => 'AI 建議檔名 (SEO 友善)',
    'label_ai_suggest_desc' => 'AI 生成 SEO 摘要',
    'label_ai_suggest_content' => 'AI 修潤後內容',
    'label_ai_suggest_tags' => 'AI 擷取標籤',
    'ai_analyzing' => 'AI 正在思考中...',
    'ai_disabled' => 'AI 功能未啟用，請檢查 config.php 設定。',
    'error_ai_quota_exceeded' => 'AI 服務額度已達上限 (429)，請稍後再試。若持續發生，請檢查 API Key 狀態。',
    'error_ai_service_busy' => 'AI 服務目前繁忙或連線逾時，請再試一次。',
    'vibe_info' => '本系統由 Gemini CLI 與 Gemini AI 模型 Vibe Coding 實作而成',

    // Migrate Tool
    'migrate_title' => '資料遷移工具',
    'migrate_info_title' => '說明',
    'migrate_desc' => '此功能會將「檔案系統」的內容遷移至指定的資料庫（MySQL 或 SQLite）。',
    'migrate_warn' => '注意：若資料庫中已有同檔名的文章，將會進行更新 (Update)；若無則新增 (Insert)。',
    'db_status' => '目標資料庫狀態',
    'btn_start_migration' => '🚀 開始匯入資料',
    'confirm_start_migration' => '確定要開始匯入嗎？這可能需要一點時間。',
    'btn_db_unreachable' => '無法連線至資料庫',
    'log_header' => '執行日誌',
    'log_connecting' => '正在連線到資料庫...', 
    'log_connected' => '連線成功!',
    'log_file_missing' => '找不到索引檔: %s',
    'log_start_process' => '開始處理 %d 篇文章...', 
    'log_imported' => '已匯入: %s',
    'log_failed' => '失敗 [%s]: %s',
    'log_complete' => '匯入完成! 成功: %d',
    'log_sys_error' => '系統錯誤: %s',

    // Migrate Tool - New
    'migrate_export_to_db' => '1. 匯出至資料庫 (File &rarr; DB)',
    'migrate_target_db' => '目標資料庫:',
    'migrate_restore_from_db' => '2. 從資料庫還原 (DB &rarr; File)',
    'migrate_source_db' => '來源資料庫:',
    'migrate_current_mode' => '當前模式：',
    'migrate_export_data' => '1. 匯出資料 (Export)',
    'migrate_export_desc' => '將當前資料庫內容匯出至...',
    'migrate_target_loc' => '目標位置:',
    'migrate_import_data' => '2. 匯入資料 (Import)',
    'migrate_import_desc' => '從外部來源匯入至當前資料庫...',
    'migrate_source_loc' => '來源位置:',
    'btn_start_restore' => '📥 開始還原',
    'btn_exec_export' => '📤 執行匯出',
    'btn_exec_import' => '📥 執行匯入',
    'confirm_export_warn' => '確定要匯出嗎？目標資料將被覆寫/更新。',
    'confirm_import_warn' => '確定要匯入嗎？當前資料庫的同名文章將被更新。',
    'confirm_restore_warn' => '確定要還原嗎？這將覆寫 contents 目錄。',
    'log_db_connect_fail' => '無法連線至來源資料庫',
    'log_target_connect_fail' => '目標資料庫連線失敗: %s',
    'log_target_connect_success' => '目標資料庫連線成功: %s',
    'log_reading_source' => '讀取來源資料庫...',
    'log_found_posts' => '共找到 %d 篇文章',
    'log_exported' => '已匯出: %s',
    'log_export_complete' => '匯出完成! index_post.txt 已更新。',
    'log_prepare_migration' => '準備遷移: %s -> %s',
    'log_source_count' => '來源資料共 %d 筆',
    'log_migration_success' => '遷移成功: %s',
    'log_migration_fail' => '遷移失敗: %s',
    'log_migration_complete' => '資料庫遷移完成!',
    'log_migration_error' => '遷移過程發生錯誤: %s',

    // SQLite Init
    'sqlite_init_title' => 'SQLite 資料庫初始化',
    'sqlite_init_msg' => '您已啟用 SQLite 模式，但資料庫檔案尚未建立或初始化。',
    'sqlite_enter_pass' => '請輸入後台管理密碼以繼續：',
    'sqlite_verify_btn' => '驗證身分',
    'sqlite_init_options' => '初始化選項',
    'sqlite_import_file' => '📂 從檔案系統匯入',
    'sqlite_import_file_desc' => '將現有檔案文章轉入 SQLite',
    'sqlite_import_mysql' => '🐬 從 MySQL 資料庫匯入',
    'sqlite_import_mysql_desc' => '複製 MySQL 資料到 SQLite',
    'sqlite_clean_install' => '🆕 全新安裝',
    'sqlite_clean_install_desc' => '建立空的資料庫',
    'sqlite_goto_admin' => '進入後台管理',
    'sqlite_auth_fail' => '管理員驗證失敗',
    'sqlite_init_success' => 'SQLite 資料庫初始化成功！',
    'sqlite_init_fail' => '初始化失敗: %s',
    'sqlite_conn_fail' => '無法建立 SQLite 連線，請檢查路徑權限。',
    'sqlite_sample_title' => '歡迎使用 BaxerMux Blog (SQLite版)',
    'sqlite_sample_content' => '<p>這是 SQLite 版本的範例文章。</p>',

    // Admin Index Hardcoded
    'stat_mode_file' => '模式: 檔案系統',
    'stat_path' => '路徑: contents/',
    'stat_log' => '日誌: index_post.txt',
    'stat_type' => '類型: %s',
    'stat_ver' => '版本: %s',
    'stat_driver' => '驅動: %s',

    // Health Check New
    'health_php_pdo_missing' => 'PHP PDO Extension 未安裝',
    'health_php_mysql_missing' => 'PHP PDO MySQL Driver 未安裝',
    'health_sqlite_config_missing' => '設定檔 $sqlite_path 未設定',
    'health_php_sqlite_missing' => 'PHP PDO SQLite Driver 未安裝',
    'health_sqlite_file_missing' => 'SQLite 檔案遺失',
    'health_sqlite_ready' => 'SQLite 就緒 (文章數: %d)',
    'health_sqlite_table_missing' => 'SQLite 資料表遺失',
    'health_sqlite_error' => 'SQLite 錯誤: %s',
    'health_album_ready' => '相簿服務已就緒 (連線正常)',
    'health_album_not_set' => '相簿服務路徑未設定',
    'health_album_not_found' => '相簿服務路徑不存在',

    'album_service_title' => '相簿服務',
    'album_manage_btn' => '管理',
    'album_manage_hint' => '前往相簿管理後台 &rarr;',
    'btn_pick_from_album' => '從相簿挑選圖片',
    'modal_album_picker_title' => '從相簿挑選圖片',
    'btn_back_to_albums' => '返回相簿列表',
    'album_loading' => '載入相簿中...',
    'photo_loading' => '載入照片中...',
    'no_albums_found' => '目前沒有任何相簿。',
    'no_photos_found' => '此相簿目前沒有照片。',
    'label_album_name' => '相簿：',
    'btn_direct_upload' => '直接上傳到此相簿',
    'uploading_wait' => '正在上傳並產生縮圖...',
    'msg_selected' => '選中：',
    'btn_size_original' => '原圖',
    'btn_size_large' => '大 (1600px)',
    'btn_size_medium' => '中 (800px)',
    'close_btn' => '關閉',

    // Backup Tool
    'nav_backup' => '📦 備份還原',
    'nav_settings' => '⚙️ 網站設定',
    'backup_title' => '系統備份',
    
    // Settings
    'settings_title' => '網站系統設定',
    'section_backend' => '後端核心設定 (config.php)',
    'label_blog_title' => 'Blog 網站標題',
    'label_blog_description' => 'Blog SEO 描述',
    'label_blog_introduce' => 'Blog 簡介 (特色說明)',
    'section_frontend' => '前端介面設定 (config.js)',
    'label_api_type' => '資料來源模式 (API Type)',
    'label_blog_lang' => '部落格語系 (Blog Language)',
    'label_timezone' => '時區 (Timezone)',
    'label_album_path' => '相簿服務路徑',
    'hint_album_path' => '設定相簿服務相對於 Blog 根目錄的路徑 (預設為 album/)。',
    'label_posts_per_page' => '每頁文章數量 (後端)',
    'hint_posts_per_page' => '設定動態模式下，伺服器 API 每頁回傳的文章篇數。',
    'label_blog_favicon' => 'Blog 圖示路徑 (Favicon)',
    'hint_blog_favicon' => '設定網站的 Favicon 路徑 (預設為 /static/icon-192.png)。',
    'label_posts_per_page_js' => '每頁文章數量 (前端)',
    'hint_posts_per_page_js' => '主要用於「Static JSON」純靜態模式，控制瀏覽器端的分頁顯示。',
    'lang_zh_tw' => '繁體中文 (Traditional Chinese)',
    'lang_en_us' => '英文 (English)',
    'label_theme' => '網站主題 (Theme)',
    'label_cse_id' => 'Google 搜尋引擎 ID (CSE ID)',
    'label_guestbook_plugin' => '留言板插件路徑',
    'hint_guestbook_plugin' => '設定 MessageBoard 插件腳本的路徑 (留空則不載入)。',
    'label_guestbook_per_page' => '留言板每頁筆數',
    'msg_settings_saved' => '設定已成功儲存！',
    'section_ai' => 'AI 輔助功能設定 (Google Gemini)',
    'label_ai_enabled' => '啟用 AI 輔助優化功能',
    'label_ai_api_key' => 'Gemini API Key',
    'label_ai_model' => '選擇 AI 專家模型',
    'hint_ai_model' => '請點擊上方按鈕抓取最新可用的模型清單。',
    'hint_ai_api_key' => '請至 Google AI Studio 申請 API Key。',
    'error_config_write' => '寫入 config.js 失敗，請檢查檔案權限。',
    'opt_api_file' => '檔案系統 (File System)',
    'opt_api_db' => 'MySQL 資料庫',
    'opt_api_sqlite' => 'SQLite 資料庫',
    'btn_save_settings' => '儲存設定',
    'backup_create_title' => '建立新備份',
    'backup_desc' => '系統將依據目前模式 (檔案或資料庫) 打包所有必要資料與資源。過程可能需要幾分鐘。',
    'backup_confirm' => '確定要開始備份嗎？請耐心等候執行完成。',
    'btn_create_backup' => '建立備份壓縮檔',
    'backup_list_title' => '現現有備份列表',
    'backup_success' => '備份成功',
    'backup_fail' => '備份失敗，請檢查目錄權限。',
    'backup_deleted' => '備份檔已刪除。',
    'col_filename' => '檔案名稱',
    'col_size' => '大小',
    'col_time' => '建立時間',
    'btn_download' => '下載',
    'confirm_delete_backup' => '確定要刪除此備份檔嗎？',
    'no_backups' => '目前沒有備份檔案。',
    'btn_restore' => '還原',
    'confirm_restore_title' => '確定要還原此備份嗎？',
    'confirm_restore_text' => '這將會覆寫目前的資料與檔案！',
    'restore_success' => '系統還原成功！',
    'restore_fail' => '還原失敗。可能是格式錯誤或 ZIP 無法開啟。',
    'loading_backup' => '正在打包備份中，請稍候...',
    'loading_restore' => '正在還原系統中，請勿關閉視窗...',
    'loading_upload' => '正在上傳備份檔，請稍候...',
    'btn_confirm_yes' => '確定執行',
    'btn_confirm_cancel' => '取消',
    'backup_upload_title' => '上傳備份檔',
    'backup_upload_desc' => '您可以上傳來自其他主機的備份檔 (ZIP 格式) 進行還原。',
    'php_ini_hint_title' => 'PHP 設定提示',
    'php_ini_hint_desc' => '若您上傳的檔案較大，請確保 php.ini 中的以下參數已適當調整，修改後請重啟伺服器：',
    'php_ini_hint_example' => '範例設定：',
    'php_ini_hint_fail' => '若無法修改設定或檔案仍超過限制，請使用 FTP 上傳檔案至 backup 目錄後再執行還原。',
    'btn_select_file' => '選擇檔案',
    'btn_upload' => '上傳',
    'upload_success' => '備份檔上傳成功！',
    'upload_fail' => '上傳失敗！原因可能為：檔案超過系統限制 (%s) 或目錄權限不足。若檔案過大，請改用 FTP 上傳至 backup 目錄。',
    'upload_err_format' => '錯誤：僅允許 ZIP 檔案。',
    'upload_limit_hint' => '注意：系統上傳上限約為 %s。若備份檔超過此大小，上傳將會失敗，請改用 FTP 或其他方式將檔案放入 backup 目錄。',
    'op_success' => '操作成功',
    'op_error' => '操作失敗',

    // Account settings
    'label_admin_account' => '管理者帳號設定',
    'label_new_username' => '新帳號',
    'label_new_password' => '新密碼',
    'hint_password_keep' => '若不修改密碼請留空',
    'btn_save_account' => '更新帳號密碼',
    'msg_account_updated' => '管理員帳號密碼已成功更新！',

    // Build Tool (SSG)
    'nav_build' => '🔨 網站建置',
    'build_title' => '靜態網頁建置 (SSG)',
    'build_desc' => '此工具會根據目前的文章資料，手動觸發靜態 HTML 網頁與 JSON API 的生成。',
    'label_build_options' => '建置選項',
    'opt_force_all' => '強制全部重生 (忽略快取)',
    'opt_update_json' => '更新 JSON API (data.json)',
    'opt_force_global' => '強制重生全域頁面 (首頁/列表頁)',
    'label_select_posts' => '選擇特定文章 (若不勾選則掃描全部變更)',
    'btn_start_build' => '🚀 開始執行建置',
    'build_log_title' => '建置日誌 (Build Log)',
    'build_running' => '建置執行中，請稍候...',
    'build_complete' => '建置執行完成！',
    'col_select' => '選取',
    'filter_all' => '全部',
    'filter_published' => '僅發布',
    'badge_no_static' => '靜態網頁未建立',
    'stat_no_static' => '未建置',

    // Security Warning
    'warn_install_file_exists' => '⚠️ 安全警告：安裝檔案 (install.php) 仍然存在。',
    'warn_install_file_exists_desc' => '為了確保系統安全，請在完成安裝後手動將根目錄下的 <code>install.php</code> 刪除。',
];