<?php
// langs/admin/en_US.php
return [
    // Login
    'login_title' => 'Blog Admin Panel',
    'login_username' => 'Username',
    'login_password' => 'Password',
    'login_mode' => 'Management Mode',
    'login_btn' => 'Login',
    'login_back_home' => 'Back to Blog Home',
    'error_auth_fail' => 'Invalid username or password.',
    'error_mode_unavailable' => 'Selected mode is currently unavailable. Please check system health.',
    'mode_db' => 'Database',
    'mode_file' => 'File System',
    'db_init_msg' => 'Database not initialized.',
    'db_init_link' => 'Click here to initialize',
    'file_init_msg' => 'File system structure incomplete.',
    'file_init_link' => 'Click here to build structure',
    'select_lang' => 'Language',

    // Health Check
    'health_db_connected' => 'Connected (Posts: %d)',
    'health_db_table_missing' => 'Connected, but table \'blog_posts\' missing',
    'health_db_conn_fail' => 'Connection Failed: %s',
    'health_file_ok' => 'File Structure Valid',
    'health_file_missing_index' => 'Missing contents/index_post.txt',
    'health_file_missing_posts' => 'Missing contents/post_files directory',
    'health_file_missing_cat' => 'Missing category directory',

    // Navigation & Layout
    'nav_brand' => 'Blog Admin',
    'nav_dashboard' => '📊 Dashboard',
    'nav_posts' => '📝 Posts',
    'nav_categories' => '📂 Categories',
    'nav_import' => '🔄 Data Migration',
    'nav_preview' => '🌍 Preview Site',
    'nav_logout' => '🚪 Logout',
    'mode_label' => 'Mode',
    'mode_db_short' => 'Database',
    'mode_file_short' => 'File System',

    // Dashboard
    'welcome_msg' => 'Welcome Back',
    'stat_posts' => 'Total Posts',
    'stat_posts_sub' => 'published posts',
    'stat_db_size' => 'DB Size',
    'stat_disk_free' => 'Disk Free',
    'stat_disk_total' => 'Total',
    'stat_connection' => 'Connection Info',
    'not_applicable' => 'N/A',
    'recent_posts_title' => '🚀 Recent Posts',
    'col_date' => 'Date',
    'col_title' => 'Title',
    'no_posts' => 'No posts found.',
    'view_all_posts' => 'Manage All Posts',

    // Posts Management
    'posts_list_title' => '📂 Post List',
    'btn_new_post' => '+ New Post',
    'msg_deleted' => 'Post deleted successfully.',
    'col_post_info' => 'Post Info (Title/File/Desc)',
    'col_category' => 'Category',
    'col_tags' => 'Tags',
    'col_action' => 'Actions',
    'no_title' => 'No Title',
    'btn_edit' => 'Edit',
    'btn_delete' => 'Delete',
    'confirm_delete_title' => 'Are you sure?',
    'confirm_delete_text' => 'You won\'t be able to revert this!',
    'confirm_yes' => 'Yes, delete it!',
    'confirm_cancel' => 'Cancel',
    'swal_deleted_title' => 'Deleted!',
    'swal_deleted_text' => 'Your post has been deleted.',

    // Categories Management
    'cat_title' => '📂 Categories',
    'btn_add_cat' => '+ New Category',
    'cat_hint' => 'Hint: Manage your categories here. You can add, rename, or remove categories. Removing a category will NOT delete the posts within it.',
    'cat_count_suffix' => 'posts',
    'btn_rename' => 'Rename',
    'btn_remove' => 'Remove',
    'no_categories' => 'No categories found.',
    
    // Modals
    'modal_create_title' => 'New Category',
    'modal_cat_name' => 'Category Name',
    'btn_create' => 'Create',
    'modal_rename_title' => 'Rename Category',
    'modal_old_name' => 'Old Name',
    'modal_new_name' => 'New Name',
    'modal_rename_warn' => 'Warning: This will update all posts associated with this category.',
    'btn_confirm_modify' => 'Update',
    'modal_remove_title' => 'Remove Category',
    'modal_remove_confirm' => 'Are you sure you want to remove ',
    'modal_remove_confirm_suffix' => '?',
    'modal_remove_hint' => 'This will remove the category tag from all posts, but the posts themselves will remain.',
    'btn_confirm_remove' => 'Remove',

    // Messages
    'msg_rename_success' => 'Successfully renamed category from \"%s\" to \"%s\".',
    'msg_rename_fail' => 'Rename failed or category not found.',
    'msg_remove_success' => 'Successfully removed category \"%s\".',
    'msg_remove_fail' => 'Remove failed or category not found.',
    'msg_create_success' => 'Successfully created category \"%s\".',
    'msg_create_fail' => 'Creation failed. Category might already exist.',

    // Post Edit
    'edit_title_new' => 'New Post',
    'edit_title_edit' => 'Edit Post',
    'post_not_found' => 'Post not found',
    'breadcrumb_home' => 'Posts',
    'label_post_title' => 'Title',
    'label_filename' => 'Filename (Leave empty for auto-generation)',
    'label_post_date' => 'Date',
    'label_html_content' => 'HTML Content',
    'hint_html_content' => 'Enter raw HTML here. Use &lt;!--more--&gt; for summary break.',
    'label_categories' => 'Categories',
    'label_add_category' => 'Add Category',
    'ph_new_category' => 'New category name',
    'label_tags' => 'Tags',
    'ph_tags' => 'Comma separated, e.g., Photo, Life, Tech',
    'label_desc' => 'Meta Description',
    'btn_cancel' => 'Cancel',
    'btn_save' => 'Save Post',

    // Vibe Info
    'vibe_info' => 'Vibe coded with Gemini CLI & Gemini AI Models',

    // Migrate Tool
    'migrate_title' => 'Data Migration Tool',
    'migrate_info_title' => 'Info',
    'migrate_desc' => 'Migrates content from \"File System\" to the designated database (MySQL or SQLite).',
    'migrate_warn' => 'Note: If a post with the same filename exists in DB, it will be UPDATED. Otherwise, it will be INSERTED.',
    'db_status' => 'Target Database Status',
    'btn_start_migration' => '🚀 Start Migration',
    'confirm_start_migration' => 'Are you sure? This might take a while.',
    'btn_db_unreachable' => 'Database Unreachable',
    'log_header' => 'Execution Log',
    'log_connecting' => 'Connecting to database...', 
    'log_connected' => 'Connected successfully!',
    'log_file_missing' => 'Index file not found: %s',
    'log_start_process' => 'Processing %d posts...', 
    'log_imported' => 'Imported: %s',
    'log_failed' => 'Failed [%s]: %s',
    'log_complete' => 'Migration Complete! Success: %d',
    'log_sys_error' => 'System Error: %s',

    // Migrate Tool - New
    'migrate_export_to_db' => '1. Export to DB (File &rarr; DB)',
    'migrate_target_db' => 'Target DB:',
    'migrate_restore_from_db' => '2. Restore from DB (DB &rarr; File)',
    'migrate_source_db' => 'Source DB:',
    'migrate_current_mode' => 'Current Mode:',
    'migrate_export_data' => '1. Export Data',
    'migrate_export_desc' => 'Export current DB content to...',
    'migrate_target_loc' => 'Target:',
    'migrate_import_data' => '2. Import Data',
    'migrate_import_desc' => 'Import from external source to current DB...',
    'migrate_source_loc' => 'Source:',
    'btn_start_restore' => '📥 Start Restore',
    'btn_exec_export' => '📤 Execute Export',
    'btn_exec_import' => '📥 Execute Import',
    'confirm_export_warn' => 'Are you sure? Target data will be overwritten/updated.',
    'confirm_import_warn' => 'Are you sure? Existing posts with same filename will be updated.',
    'confirm_restore_warn' => 'Are you sure? This will overwrite the contents directory.',
    'log_db_connect_fail' => 'Cannot connect to source database',
    'log_target_connect_fail' => 'Target database connection failed: %s',
    'log_target_connect_success' => 'Target database connected: %s',
    'log_reading_source' => 'Reading source database...',
    'log_found_posts' => 'Found %d posts',
    'log_exported' => 'Exported: %s',
    'log_export_complete' => 'Export complete! index_post.txt updated.',
    'log_prepare_migration' => 'Preparing migration: %s -> %s',
    'log_source_count' => 'Source data: %d rows',
    'log_migration_success' => 'Success: %s',
    'log_migration_fail' => 'Fail: %s',
    'log_migration_complete' => 'Database migration complete!',
    'log_migration_error' => 'Migration error: %s',

    // SQLite Init
    'sqlite_init_title' => 'SQLite Initialization',
    'sqlite_init_msg' => 'You have enabled SQLite mode, but the database file is not initialized.',
    'sqlite_enter_pass' => 'Please enter admin password to continue:',
    'sqlite_verify_btn' => 'Verify',
    'sqlite_init_options' => 'Initialization Options',
    'sqlite_import_file' => '📂 Import from File System',
    'sqlite_import_file_desc' => 'Import existing file posts to SQLite',
    'sqlite_import_mysql' => '🐬 Import from MySQL',
    'sqlite_import_mysql_desc' => 'Copy data from MySQL to SQLite',
    'sqlite_clean_install' => '🆕 Clean Install',
    'sqlite_clean_install_desc' => 'Create an empty database',
    'sqlite_goto_admin' => 'Go to Admin Panel',
    'sqlite_auth_fail' => 'Authentication failed',
    'sqlite_init_success' => 'SQLite database initialized successfully!',
    'sqlite_init_fail' => 'Initialization failed: %s',
    'sqlite_conn_fail' => 'Cannot connect to SQLite. Check path permissions.',
    'sqlite_sample_title' => 'Welcome to BaxerMux Blog (SQLite)',
    'sqlite_sample_content' => '<p>This is a sample post for SQLite version.</p>',

    // Admin Index Hardcoded
    'stat_mode_file' => 'Mode: File System',
    'stat_path' => 'Path: contents/',
    'stat_log' => 'Log: index_post.txt',
    'stat_type' => 'Type: %s',
    'stat_ver' => 'Ver: %s',
    'stat_driver' => 'Driver: %s',

    // Health Check New
    'health_php_pdo_missing' => 'PHP PDO Extension missing',
    'health_php_mysql_missing' => 'PHP PDO MySQL Driver missing',
    'health_sqlite_config_missing' => 'Config $sqlite_path not set',
    'health_php_sqlite_missing' => 'PHP PDO SQLite Driver missing',
    'health_sqlite_file_missing' => 'SQLite file missing',
    'health_sqlite_ready' => 'SQLite Ready (Posts: %d)',
    'health_sqlite_table_missing' => 'SQLite Tables Missing',
    'health_sqlite_error' => 'SQLite Error: %s',
];