<?php
// langs/admin/zh_TW.php
return [
    // Login
    'login_title' => 'Blog 後台管理',
    'login_username' => '帳號',
    'login_password' => '密碼',
    'login_mode' => '管理模式',
    'login_btn' => '登入',
    'login_back_home' => '回到部落格首頁',
    'error_auth_fail' => '帳號或密碼錯誤',
    'error_mode_unavailable' => '選定的管理模式目前不可用，請檢查系統環境。',
    'mode_db' => '資料庫 (Database)',
    'mode_file' => '檔案系統 (File System)',
    'db_init_msg' => '資料庫尚未初始化。',
    'db_init_link' => '點擊此處進行初始化設定',
    'file_init_msg' => '檔案系統結構不完整。',
    'file_init_link' => '點擊此處進行建構設定',
    'select_lang' => '語言 / Language',

    // Health Check
    'health_db_connected' => '連線成功 (文章數: %d)',
    'health_db_table_missing' => '連線成功，但找不到資料表 \'blog_posts\'',
    'health_db_conn_fail' => '連線失敗: %s',
    'health_file_ok' => '檔案結構完整',
    'health_file_missing_index' => '缺少 contents/index_post.txt',
    'health_file_missing_posts' => '缺少 contents/post_files 目錄',
    'health_file_missing_cat' => '缺少 category 目錄',

    // Navigation & Layout
    'nav_brand' => 'Blog Admin',
    'nav_dashboard' => '📊 儀表板',
    'nav_posts' => '📝 文章管理',
    'nav_categories' => '📂 分類管理',
    'nav_import' => '🔄 資料匯入',
    'nav_preview' => '🌍 預覽網站',
    'nav_logout' => '🚪 登出',
    'mode_label' => '模式',
    'mode_db_short' => '資料庫',
    'mode_file_short' => '檔案系統',

    // Dashboard
    'welcome_msg' => '歡迎回來',
    'stat_posts' => '文章總數',
    'stat_posts_sub' => '篇已發布文章',
    'stat_db_size' => '資料庫大小',
    'stat_disk_free' => '磁碟剩餘空間',
    'stat_disk_total' => '總容量',
    'stat_connection' => '連線資訊',
    'not_applicable' => '不適用',
    'recent_posts_title' => '🚀 最新發布文章',
    'col_date' => '發布日期',
    'col_title' => '標題',
    'no_posts' => '目前沒有文章',
    'view_all_posts' => '管理所有文章',

    // Posts Management
    'posts_list_title' => '📂 文章列表',
    'btn_new_post' => '+ 撰寫新文章',
    'msg_deleted' => '文章已刪除。',
    'col_post_info' => '文章資訊 (標題/檔名/描述)',
    'col_category' => '分類',
    'col_tags' => '標籤',
    'col_action' => '操作',
    'no_title' => '無標題',
    'btn_edit' => '編輯',
    'btn_delete' => '刪除',
    'confirm_delete_title' => '確定要刪除這篇文章嗎？',
    'confirm_delete_text' => '這個動作無法復原！',
    'confirm_yes' => '是的，刪除它！',
    'confirm_cancel' => '取消',
    'swal_deleted_title' => '已刪除！',
    'swal_deleted_text' => '文章已成功移除。',

    // Categories Management
    'cat_title' => '📂 分類管理',
    'btn_add_cat' => '+ 新增分類',
    'cat_hint' => '提示：此處列出系統中的所有分類。您可以新增、改名或移除分類。請注意，移除分類不會刪除該分類下的文章。',
    'cat_count_suffix' => '篇文章',
    'btn_rename' => '改名',
    'btn_remove' => '移除',
    'no_categories' => '目前沒有任何分類資料。',
    
    // Modals
    'modal_create_title' => '新增分類',
    'modal_cat_name' => '分類名稱',
    'btn_create' => '建立',
    'modal_rename_title' => '重新命名分類',
    'modal_old_name' => '原名稱',
    'modal_new_name' => '新名稱',
    'modal_rename_warn' => '注意：這將會批次修改所有相關的文章資料。',
    'btn_confirm_modify' => '確認修改',
    'modal_remove_title' => '移除分類',
    'modal_remove_confirm' => '您確定要移除分類', 
    'modal_remove_confirm_suffix' => '嗎？',
    'modal_remove_hint' => '這將會從所有相關的文章中刪除此分類標籤，但文章本身不會被刪除。',
    'btn_confirm_remove' => '確認移除',

    // Messages
    'msg_rename_success' => '成功將分類由「%s」改為「%s」。',
    'msg_rename_fail' => '修改失敗或未找到目標。',
    'msg_remove_success' => '成功移除分類「%s」。',
    'msg_remove_fail' => '移除失敗或未找到目標。',
    'msg_create_success' => '成功建立新分類「%s」。',
    'msg_create_fail' => '建立失敗，可能分類已存在。',

    // Post Edit
    'edit_title_new' => '撰寫新文章',
    'edit_title_edit' => '編輯文章',
    'post_not_found' => '文章不存在',
    'breadcrumb_home' => '文章管理',
    'label_post_title' => '文章標題',
    'label_filename' => '檔案名稱 (留空則自動以時間生成)',
    'label_post_date' => '發布時間',
    'label_html_content' => 'HTML 內容',
    'hint_html_content' => '請直接輸入 HTML 原始碼。可使用 &lt;!--more--&gt; 設定摘要分隔線。',
    'label_categories' => '文章分類',
    'label_add_category' => '新增分類',
    'ph_new_category' => '輸入新分類名稱',
    'label_tags' => '標籤 (Tags)',
    'ph_tags' => '使用逗號分隔，例如: 攝影, 開箱, 心得',
    'label_desc' => '摘要描述 (Meta Description)',
    'btn_cancel' => '取消',
    'btn_save' => '儲存文章',

    // Vibe Info
    'vibe_info' => '本系統由 Gemini CLI 與 Gemini AI 模型 Vibe Coding 實作而成',

    // Migrate Tool
    'migrate_title' => '資料匯入 (File to DB)',
    'migrate_info_title' => '說明',
    'migrate_desc' => '此功能會讀取目前的「檔案系統」內容 (contents, category)，並將其解析後寫入至設定的 MySQL 資料庫中。',
    'migrate_warn' => '注意：若資料庫中已有同檔名的文章，將會進行更新 (Update)；若無則新增 (Insert)。',
    'db_status' => '目標資料庫狀態',
    'btn_start_migration' => '🚀 開始匯入資料',
    'confirm_start_migration' => '確定要開始匯入嗎？這可能需要一點時間。',
    'btn_db_unreachable' => '無法連線至資料庫',
    'log_header' => '執行日誌',
    'log_connecting' => '正在連線到資料庫...', 
    'log_connected' => '連線成功!',
    'log_file_missing' => '找不到索引檔: %s',
    'log_start_process' => '開始處理 %d 篇文章...', 
    'log_imported' => '已匯入: %s',
    'log_failed' => '失敗 [%s]: %s',
    'log_complete' => '匯入完成! 成功: %d',
    'log_sys_error' => '系統錯誤: %s',
];
