<?php
require_once 'auth.php';
requireAlbumLogin();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header('Location: albums.php');
    exit;
}

validateCSRFRequest();

$action = isset($_POST['action']) ? $_POST['action'] : '';
$collectionDir = __DIR__ . '/../Collection';

switch ($action) {
    case 'create_album':
        $dirName = isset($_POST['dir_name']) ? trim($_POST['dir_name']) : '';
        $displayName = isset($_POST['display_name']) ? trim($_POST['display_name']) : '';
        $desc = isset($_POST['description']) ? trim($_POST['description']) : '';

        if (empty($dirName) || !preg_match('/^[A-Za-z0-9_-]+$/', $dirName)) {
            die("Invalid directory name.");
        }

        $targetDir = $collectionDir . '/' . $dirName;
        if (is_dir($targetDir)) {
            die("Album already exists.");
        }

        mkdir($targetDir, 0777, true);
        mkdir($targetDir . '/Thumbnail', 0777, true);

        // Save metadata
        $metaContent = "$displayName|$desc||" . date('Ymd');
        file_put_contents($targetDir . '/comment_album.txt', $metaContent);

        header('Location: albums.php');
        break;

    case 'delete_album':
        $id = isset($_POST['album_id']) ? trim($_POST['album_id']) : '';
        if (empty($id) || strpos($id, '..') !== false) die("Invalid ID");

        $targetDir = $collectionDir . '/' . $id;
        if (is_dir($targetDir)) {
            // Recursive delete
            $files = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($targetDir, RecursiveDirectoryIterator::SKIP_DOTS),
                RecursiveIteratorIterator::CHILD_FIRST
            );

            foreach ($files as $fileinfo) {
                $todo = ($fileinfo->isDir() ? 'rmdir' : 'unlink');
                $todo($fileinfo->getRealPath());
            }
            rmdir($targetDir);
        }
        header('Location: albums.php');
        break;

    case 'update_album_info':
        $id = isset($_POST['album_id']) ? trim($_POST['album_id']) : '';
        $newDirName = isset($_POST['new_dir_name']) ? trim($_POST['new_dir_name']) : ''; // Optional rename
        $displayName = isset($_POST['display_name']) ? trim($_POST['display_name']) : '';
        $desc = isset($_POST['description']) ? trim($_POST['description']) : '';
        $date = isset($_POST['date']) ? trim($_POST['date']) : '';
        
        if (empty($id) || !is_dir($collectionDir . '/' . $id)) die("Album not found");

        $targetDir = $collectionDir . '/' . $id;

        // Rename logic if new_dir_name is provided and different
        if (!empty($newDirName) && $newDirName !== $id) {
             if (!preg_match('/^[A-Za-z0-9_-]+$/', $newDirName)) die("Invalid new directory name.");
             $newTargetDir = $collectionDir . '/' . $newDirName;
             if (is_dir($newTargetDir)) die("Target directory name already exists.");
             
             rename($targetDir, $newTargetDir);
             $targetDir = $newTargetDir; // Update target for meta writing
             $id = $newDirName; // Update ID for redirect
        }

        // Read existing to preserve cover if possible
        $cover = '';
        $metaFile = $targetDir . '/comment_album.txt';
        if (file_exists($metaFile)) {
            $parts = explode('|', file_get_contents($metaFile));
            if (isset($parts[2])) $cover = $parts[2];
        }

        $newContent = "$displayName|$desc|$cover|$date";
        file_put_contents($targetDir . '/comment_album.txt', $newContent);

        header('Location: albums.php');
        break;

    case 'update_settings':
        // ... (保持不變)
        $theme = isset($_POST['theme']) ? trim($_POST['theme']) : 'album';
        $apiType = isset($_POST['api_type']) ? trim($_POST['api_type']) : 'json';
        $itemsPerPage = isset($_POST['items_per_page']) ? (int)$_POST['items_per_page'] : 24;
        $concurrentDownloads = isset($_POST['concurrent_downloads']) ? (int)$_POST['concurrent_downloads'] : 3;

        $configFile = realpath(__DIR__ . '/../config/config.js');
        if (!$configFile) $configFile = __DIR__ . '/../config/config.js';

        $jsContent = "/**\n * Baxermux Album Configuration\n * Automatically generated by Admin Panel\n */\n";
        $jsContent .= "const albumConfig = {\n";
        $jsContent .= "    theme: '" . addslashes($theme) . "',\n";
        $jsContent .= "    api_type: '" . addslashes($apiType) . "',\n";
        $jsContent .= "    items_per_page: " . $itemsPerPage . ",\n";
        $jsContent .= "    concurrent_downloads: " . $concurrentDownloads . "\n";
        $jsContent .= "};\n";

        if (file_put_contents($configFile, $jsContent) === false) die("Error writing to config.js");
        header('Location: settings.php?status=success');
        break;

    case 'update_backend_settings':
        $title = isset($_POST['album_title']) ? trim($_POST['album_title']) : '';
        $description = isset($_POST['album_description']) ? trim($_POST['album_description']) : '';
        $introduce = isset($_POST['album_introduce']) ? trim($_POST['album_introduce']) : '';
        $preview = isset($_POST['album_preview']) ? trim($_POST['album_preview']) : '';
        $siteUrl = isset($_POST['album_site_url']) ? trim($_POST['album_site_url']) : '';
        $lang = isset($_POST['album_lang']) ? trim($_POST['album_lang']) : 'zh_TW';
        $timezone = isset($_POST['album_timezone']) ? trim($_POST['album_timezone']) : 'Asia/Taipei';

        $phpFile = __DIR__ . '/../config/config.php';
        
        // 讀取現有配置以保留 admin 帳密
        $albumAdminConfig = array();
        if (file_exists($phpFile)) {
            include $phpFile;
        }

        $phpContent = "<?php\n/**\n * Baxermux Album Configuration\n * Automatically generated by Admin Panel\n */\n\n";
        $phpContent .= "// --- 後台管理員設定 ---\n";
        $phpContent .= "\$albumAdminConfig = " . var_export($albumAdminConfig, true) . ";\n\n";
        $phpContent .= "// --- 全域相簿設定 ---\n";
        $phpContent .= "\$album_title = \"" . addslashes($title) . "\";\n";
        $phpContent .= "\$album_description = \"" . addslashes($description) . "\";\n";
        $phpContent .= "\$album_introduce = \"" . addslashes($introduce) . "\";\n";
        $phpContent .= "\$album_preview = \"" . addslashes($preview) . "\";\n";
        $phpContent .= "\$album_site_url = \"" . addslashes($siteUrl) . "\";\n";
        $phpContent .= "\$album_lang = \"" . addslashes($lang) . "\";\n";
        $phpContent .= "\$album_timezone = \"" . addslashes($timezone) . "\";\n\n";
        $phpContent .= "// 設定時區\n";
        $phpContent .= "date_default_timezone_set(\$album_timezone);\n";
        $phpContent .= "?>";

        if (file_put_contents($phpFile, $phpContent) === false) die("Error writing to config.php");
        header('Location: settings.php?status=success');
        break;

    default:
        header('Location: albums.php');
}
?>
