<?php
require_once 'auth.php';
requireAlbumLogin();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header('Location: albums.php');
    exit;
}

validateCSRFRequest();

$action = isset($_POST['action']) ? $_POST['action'] : '';
$collectionDir = __DIR__ . '/../Collection';

switch ($action) {
    case 'create_album':
        $dirName = isset($_POST['dir_name']) ? trim($_POST['dir_name']) : '';
        $displayName = isset($_POST['display_name']) ? trim($_POST['display_name']) : '';
        $desc = isset($_POST['description']) ? trim($_POST['description']) : '';

        if (empty($dirName) || !preg_match('/^[A-Za-z0-9_-]+$/', $dirName)) {
            die("Invalid directory name.");
        }

        $targetDir = $collectionDir . '/' . $dirName;
        if (is_dir($targetDir)) {
            die("Album already exists.");
        }

        mkdir($targetDir, 0777, true);
        mkdir($targetDir . '/Thumbnail', 0777, true);

        // Save metadata
        $metaContent = "$displayName|$desc||" . date('Ymd');
        file_put_contents($targetDir . '/comment_album.txt', $metaContent);

        header('Location: albums.php');
        break;

    case 'delete_album':
        $id = isset($_POST['album_id']) ? trim($_POST['album_id']) : '';
        if (empty($id) || strpos($id, '..') !== false) die("Invalid ID");

        $targetDir = $collectionDir . '/' . $id;
        if (is_dir($targetDir)) {
            // Recursive delete
            $files = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($targetDir, RecursiveDirectoryIterator::SKIP_DOTS),
                RecursiveIteratorIterator::CHILD_FIRST
            );

            foreach ($files as $fileinfo) {
                $todo = ($fileinfo->isDir() ? 'rmdir' : 'unlink');
                $todo($fileinfo->getRealPath());
            }
            rmdir($targetDir);
        }
        header('Location: albums.php');
        break;

    case 'update_album_info':
        $id = isset($_POST['album_id']) ? trim($_POST['album_id']) : '';
        $newDirName = isset($_POST['new_dir_name']) ? trim($_POST['new_dir_name']) : ''; // Optional rename
        $displayName = isset($_POST['display_name']) ? trim($_POST['display_name']) : '';
        $desc = isset($_POST['description']) ? trim($_POST['description']) : '';
        $date = isset($_POST['date']) ? trim($_POST['date']) : '';
        
        if (empty($id) || !is_dir($collectionDir . '/' . $id)) die("Album not found");

        $targetDir = $collectionDir . '/' . $id;

        // Rename logic if new_dir_name is provided and different
        if (!empty($newDirName) && $newDirName !== $id) {
             if (!preg_match('/^[A-Za-z0-9_-]+$/', $newDirName)) die("Invalid new directory name.");
             $newTargetDir = $collectionDir . '/' . $newDirName;
             if (is_dir($newTargetDir)) die("Target directory name already exists.");
             
             rename($targetDir, $newTargetDir);
             $targetDir = $newTargetDir; // Update target for meta writing
             $id = $newDirName; // Update ID for redirect
        }

        // Read existing to preserve cover if possible
        $cover = '';
        $metaFile = $targetDir . '/comment_album.txt';
        if (file_exists($metaFile)) {
            $parts = explode('|', file_get_contents($metaFile));
            if (isset($parts[2])) $cover = $parts[2];
        }

        $newContent = "$displayName|$desc|$cover|$date";
        file_put_contents($targetDir . '/comment_album.txt', $newContent);

        header('Location: albums.php');
        break;

    case 'update_settings':
        $theme = isset($_POST['theme']) ? trim($_POST['theme']) : 'album';
        $apiType = isset($_POST['api_type']) ? trim($_POST['api_type']) : 'json';
        $itemsPerPage = isset($_POST['items_per_page']) ? (int)$_POST['items_per_page'] : 24;

        // Use realpath to ensure we are targeting the correct file
        $configFile = realpath(__DIR__ . '/../config.js');
        if (!$configFile) {
            // If realpath fails (file doesn't exist?), try constructing it manually
            $configFile = __DIR__ . '/../config.js';
        }

        $jsContent = "/**\n * Baxermux Album Configuration\n * Automatically generated by Admin Panel\n */\n";
        $jsContent .= "const albumConfig = {\n";
        $jsContent .= "    theme: '" . addslashes($theme) . "',\n";
        $jsContent .= "    api_type: '" . addslashes($apiType) . "',\n";
        $jsContent .= "    items_per_page: " . $itemsPerPage . "\n";
        $jsContent .= "};\n";

        if (file_put_contents($configFile, $jsContent) === false) {
            die("Error writing to config.js. Please check permissions.");
        }

        header('Location: settings.php?status=success');
        break;

    default:
        header('Location: albums.php');
}
?>
