<?php
/**
 * Album Service Version Configuration
 * Automatically generated by Gemini CLI
 */
define('ALBUM_VERSION', 'v2026.02.11.21.58');
define('ALBUM_CLI_VERSION', '0.28.0');
define('ALBUM_AI_MODEL', 'gemini-3-flash-preview');
define('ALBUM_UPDATE_TIME', '2026-02-11 21:58:50');
?>
