<?php
// 此檔案由 Gemini CLI 自動生成，請勿手動修改
// This file is automatically generated by Gemini CLI, do not edit manually

return [
    'version' => 'v2026.02.07.15.32',
    'cli_version' => '0.27.3',
    'ai_model' => 'gemini-3-flash-preview',
    'last_updated' => '2026-02-07 15:32:06', // UTC+8
];
