<?php
// admin/version_config.php
// Generated by Gemini CLI
return array(
    'version' => 'v2026.02.07.10.08',
    'cli_version' => '0.27.2',
    'model_name' => 'gemini-3-flash-preview',
    'update_time' => '2026-02-07 10:08:15 (UTC+8)'
);
